import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";

type SectionData = {
  codeType: "IPC" | "BNS";
  sectionNumber: string;
  title: string;
  bodyText: string;
};

type Props = {
  primaryTitle: string;
  changeTypeLabel: string;
  summary: string | null;
  ipc: SectionData | null;
  bns: SectionData | null;
};

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10.5,
    fontFamily: "Helvetica",
    color: "#1C1B1F",
  },
  brand: {
    fontSize: 9,
    color: "#96652E",
    letterSpacing: 1,
    marginBottom: 4,
    textTransform: "uppercase",
  },
  title: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  badge: {
    fontSize: 9,
    color: "#FFFFFF",
    backgroundColor: "#96652E",
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 10,
    alignSelf: "flex-start",
    marginBottom: 14,
    textTransform: "uppercase",
  },
  summaryBox: {
    backgroundColor: "#F3EDDE",
    padding: 10,
    borderRadius: 3,
    marginBottom: 18,
    fontSize: 10,
    lineHeight: 1.5,
    color: "#4A463F",
  },
  row: {
    flexDirection: "row",
    gap: 16,
  },
  column: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#DDD5C3",
    borderRadius: 3,
    padding: 12,
  },
  columnLabel: {
    fontSize: 8.5,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
  },
  bodyText: {
    fontSize: 9.5,
    lineHeight: 1.5,
    color: "#33312C",
  },
  emptyText: {
    fontSize: 9.5,
    fontStyle: "italic",
    color: "#9C9483",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#9C9483",
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#DDD5C3",
    paddingTop: 8,
  },
});

export function ComparisonDocument({ primaryTitle, changeTypeLabel, summary, ipc, bns }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>NyayaBridge · IPC 1860 ⇌ BNS 2023 Cross-Reference</Text>
        <Text style={styles.title}>{primaryTitle}</Text>
        <Text style={styles.badge}>{changeTypeLabel}</Text>

        {summary && <Text style={styles.summaryBox}>{summary}</Text>}

        <View style={styles.row}>
          <View style={styles.column}>
            <Text style={[styles.columnLabel, { color: "#96652E" }]}>
              IPC 1860 {ipc ? `· Sec. ${ipc.sectionNumber}` : ""}
            </Text>
            {ipc ? (
              <>
                <Text style={styles.sectionTitle}>{ipc.title}</Text>
                <Text style={styles.bodyText}>{ipc.bodyText || "No further section text beyond the title above."}</Text>
              </>
            ) : (
              <Text style={styles.emptyText}>No corresponding section.</Text>
            )}
          </View>
          <View style={styles.column}>
            <Text style={[styles.columnLabel, { color: "#1F5753" }]}>
              BNS 2023 {bns ? `· Sec. ${bns.sectionNumber}` : ""}
            </Text>
            {bns ? (
              <>
                <Text style={styles.sectionTitle}>{bns.title}</Text>
                <Text style={styles.bodyText}>{bns.bodyText || "No further section text beyond the title above."}</Text>
              </>
            ) : (
              <Text style={styles.emptyText}>No corresponding section.</Text>
            )}
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by NyayaBridge · For informational/reference purposes only — not legal advice.
          Verify with official sources (Ministry of Home Affairs / BPRD) or a legal professional
          before relying on this for any legal proceeding.
        </Text>
      </Page>
    </Document>
  );
}
